// <auto-generated />
using System;
using GerenciadorFinanceiroResidencial.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorFinanceiroResidencial.Persistence.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20260320120351_CategoryMigration")]
    partial class CategoryMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c60109c8-9e21-4e32-8930-75d9e7d2b8a1"),
                            Description = "Salário",
                            Purpose = 1
                        },
                        new
                        {
                            Id = new Guid("e0ec4138-9ff6-4dc7-baa8-d6c069bf34cf"),
                            Description = "Aluguel",
                            Purpose = 2
                        });
                });

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd539e90-9e8c-4002-a005-f1d0adbbc2df"),
                            Age = 20,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("daaafb00-298e-43db-b67e-592314389e82"),
                            Age = 21,
                            Name = "Jane Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
