// <auto-generated />
using System;
using GerenciadorFinanceiroResidencial.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorFinanceiroResidencial.Persistence.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20260320135214_TransactionMigration")]
    partial class TransactionMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f75cf24-63a9-4f40-b6d7-5ec3fbb4fd63"),
                            Description = "Salário",
                            Purpose = 1
                        },
                        new
                        {
                            Id = new Guid("c0f3fd7a-f3a7-45aa-a6f1-94f690772f15"),
                            Description = "Aluguel",
                            Purpose = 2
                        });
                });

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5f0f16c-5b4e-4902-a98f-c7df1db6f2d1"),
                            Age = 20,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("0ce7f8c7-1ad7-4f70-a170-a2dd111f0c77"),
                            Age = 21,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PersonId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("711bb67e-ae84-4c6f-816d-52b14978dcd1"),
                            Amount = 5000m,
                            CategoryId = new Guid("3f75cf24-63a9-4f40-b6d7-5ec3fbb4fd63"),
                            Description = "Salário de Junho",
                            PersonId = new Guid("d5f0f16c-5b4e-4902-a98f-c7df1db6f2d1"),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("275fa615-6416-4b78-9c43-00c555287587"),
                            Amount = 3000m,
                            CategoryId = new Guid("c0f3fd7a-f3a7-45aa-a6f1-94f690772f15"),
                            Description = "Aluguel de Junho",
                            PersonId = new Guid("0ce7f8c7-1ad7-4f70-a170-a2dd111f0c77"),
                            TransactionType = 2
                        });
                });

            modelBuilder.Entity("GerenciadorFinanceiroResidencial.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("GerenciadorFinanceiroResidencial.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GerenciadorFinanceiroResidencial.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
